;@const-symbol-strings

;Buffers
(def led-button-buffer)
(def led-footpad-buffer)
(def led-status-buffer)
(def led-front-buffer)
(def led-rear-buffer)
(def led-combined-buffer)

@const-start

(def led-loop-delay)
;config vars
(def led-enabled)
(def led-mode)
(def led-mode-idle)
(def led-mode-status)
(def led-mode-startup)
(def led-mode-button)
(def led-mode-footpad)
(def led-mall-grab-enabled)
(def led-brake-light-enabled)
(def led-brake-light-min-amps)
(def idle-timeout)
(def idle-timeout-shutoff)
(def led-status-pin)
(def led-status-num)
(def led-status-type)
(def led-status-reversed)
(def led-front-pin)
(def led-front-num)
(def led-front-type)
(def led-front-reversed)
(def led-front-strip-type)
(def led-rear-pin)
(def led-rear-num)
(def led-rear-type)
(def led-rear-reversed)
(def led-rear-strip-type)
(def led-button-pin)
(def led-button-strip-type)
(def led-footpad-pin)
(def led-footpad-num)
(def led-footpad-type)
(def led-footpad-reversed)
(def led-footpad-strip-type)
(def led-max-brightness)
(def led-update-not-running)

(def led-max-blend-count 0.0)  ; how many times to blend before new led buffer
(def led-startup-timeout)
(def led-dim-on-highbeam-ratio 0.0)
(def led-status-strip-type)
;runtime vars
(def led-current-brightness 0.0)
(def led-smoothed-brightness 0.0)
(def led-status-color '())
(def led-front-color '())
(def led-rear-color '())
(def led-button-color '())
(def led-footpad-color '())
(def next-run-time)
(def direction)
(def led-mall-grab)
(def prev-led-front-color '())
(def prev-led-rear-color '())
(def prev-led-footpad-color '())
(def target-led-front-color '())
(def target-led-rear-color '())
(def target-led-footpad-color '())
(def prev-led-button-color '())
(def target-led-button-color '())
(def combined-pins nil)
(def led-fix 1)
(def led-show-battery-charging 0)
(def led-front-highbeam-pin)
(def led-rear-highbeam-pin)

@const-end
