;@const-symbol-strings

@const-start

; Magic header
(def magic-header 445i32)
; Persistent settings

; Format: (label . (offset type default-value current-value))
(def eeprom-addrs '(
    (magic                     . (0 i magic-header))
    (crc                       . (1 i 61381))
    (can-id                    . (2  i -1))  ; if can-id < 0 then it will scan for one and pick the first.
    (accept-tos                . (3 b 0))
    (led-enabled               . (4 b 0))
    (bms-enabled               . (5 b 0))
    (pubmote-enabled           . (6 b 0))
    (led-on                    . (7 b 1))
    (led-highbeam-on           . (8 b 1))
    (led-mode                  . (9 i 0))
    (led-mode-idle             . (10 i 5))
    (led-mode-status           . (11 i 0))
    (led-mode-startup          . (12 i 9))
    (led-mode-button           . (13 i 0))
    (led-mode-footpad          . (14 i 0))
    (led-mall-grab-enabled     . (15 b 1))
    (led-brake-light-enabled   . (16 b 1))
    (led-brake-light-min-amps  . (17 f -4.0))
    (idle-timeout              . (18 i 1))
    (idle-timeout-shutoff      . (19 i 600))
    (led-brightness            . (20 f 0.8))
    (led-brightness-highbeam   . (21 f 0.8))
    (led-brightness-idle       . (22 f 0.5))
    (led-brightness-status     . (23 f 0.2))
    (led-status-pin            . (24 i 7))
    (led-status-num            . (25 i 10))
    (led-status-type           . (26 i 0))
    (led-status-reversed       . (27 b 1))
    (led-front-pin             . (28 i 8))
    (led-front-num             . (29 i 11))
    (led-front-type            . (30 i 2))
    (led-front-reversed        . (31 b 1))
    (led-front-strip-type      . (32 b 0))
    (led-rear-pin              . (33 i 9))
    (led-rear-num              . (34 i 11))
    (led-rear-type             . (35 i 2))
    (led-rear-reversed         . (36 b 1))
    (led-rear-strip-type       . (37 b 0))
    (led-button-pin            . (38 b -1))
    (led-button-strip-type     . (39 b 0))
    (led-footpad-pin           . (40 i -1))
    (led-footpad-num           . (41 i 0))
    (led-footpad-type          . (42 i 0))
    (led-footpad-reversed      . (43 b 0))
    (led-footpad-strip-type    . (44 b 0))
    (pubmote-remote-mac-a      . (45 i -1))
    (pubmote-remote-mac-b      . (46 i -1))
    (pubmote-secret-code       . (47 i -1))
    (bms-rs485-di-pin          . (48 i 16))
    (bms-rs485-ro-pin          . (49 i 8))
    (bms-rs485-dere-pin        . (50 i 17))
    (bms-wakeup-pin            . (51 i -1))
    (bms-override-soc          . (52 i 0))
    (bms-rs485-chip            . (53 b 1))
    (bms-key-a                 . (54 i -1))
    (bms-key-b                 . (55 i -1))
    (bms-key-c                 . (56 i -1))
    (bms-key-d                 . (57 i -1))
    (bms-counter-a             . (58 i -1))
    (bms-counter-b             . (59 i -1))
    (bms-counter-c             . (60 i -1))
    (bms-counter-d             . (61 i -1))
    (led-loop-delay            . (62 i 20))
    (bms-loop-delay            . (63 i 8))
    (pubmote-loop-delay        . (64 i 20))
    (can-loop-delay            . (65 i 8))
    (led-max-blend-count       . (66 i 4))
    (led-startup-timeout       . (67 i 20))
    (led-dim-on-highbeam-ratio . (68 f 0.2))
    (bms-type                  . (69 i 0))
    (led-status-strip-type     . (70 i 0))
    (bms-charge-only           . (71 b 0))
    (led-fix                   . (72 i 100))
    (led-show-battery-charging . (73 b 1))
    (led-front-highbeam-pin    . (74 i -1))
    (led-rear-highbeam-pin     . (75 i -1))
    (bms-buff-size             . (76 i 128))
    (led-max-brightness        . (77 f 0.8))
    (soc-type                  . (78 i 0))
    (cell-type                 . (79 i 0))
    (led-update-not-running    . (80 b 0))
    (log-enabled               . (81 b 0))
    (log-rate                  . (82 f 2))
    (log-append-gnss           . (83 b 0))
    (humidity-enabled          . (84 b 0))
    (humidity-sda-pin          . (85 i -1))
    (humidity-slc-pin          . (86 i -1))
))
(def runtime-vals)
(setq runtime-vals (mklist (length eeprom-addrs) -1))

(def cfg-len (length eeprom-addrs))
(def read-cfg-len 0)
(def bms-context-id -1)
(def bms-exit-flag nil)
(def humidity-exit-flag nil)
(def bms-last-activity-time (systime))
(def pubmote-context-id -1)
(def led-context-id -1)
(def led-exit-flag nil)
(def led-reinit-flag nil)
(def led-last-activity-time (systime))
(def can-context-id -1)
(def can-last-activity-time (systime))
(def bms-charge-state 0) ;0 if 100, 1 if 90
(def log-context-id -1)

; LED settings used by settings.lisp - needed otherwise they will be unbound
(def led-on)
(def led-highbeam-on)
(def led-brightness 0.0)
(def led-brightness-highbeam 0.0)
(def led-brightness-idle 0.0)
(def led-brightness-status 0.0)

(def bms-status -1)
(def bms-battery-type -1)
(def bms-battery-cycles -1)

(def humidity-context-id -1)

; State
(def log-running false)

(def hum 0)
(def hum-temp 0)

; Last input state received from the remote, for the QML input preview
(def pubmote-last-jsy 0.0)
(def pubmote-last-jsx 0.0)
(def pubmote-last-bt-c 0)
(def pubmote-last-bt-z 0)
(def pubmote-last-is-rev 0)

@const-end
