// Generated by conf/gen_conf.py - do not edit.
// Name -> FaConfig field lookup for the LispBM config extensions.
#ifndef CONF_LOOKUP_H_
#define CONF_LOOKUP_H_

#include <stddef.h>
#include "datatypes.h"

typedef enum { CFG_F32 = 0, CFG_I32, CFG_U8 } cfg_field_type;

typedef struct {
    const char *name;
    uint16_t offset;
    uint8_t type;
} cfg_field_t;

static const cfg_field_t cfg_fields[] = {
    {"led_enabled", offsetof(FaConfig, led_enabled), CFG_U8},
    {"bms_enabled", offsetof(FaConfig, bms_enabled), CFG_U8},
    {"pubmote_enabled", offsetof(FaConfig, pubmote_enabled), CFG_U8},
    {"log_enabled", offsetof(FaConfig, log_enabled), CFG_U8},
    {"humidity_enabled", offsetof(FaConfig, humidity_enabled), CFG_U8},
    {"can_id", offsetof(FaConfig, can_id), CFG_I32},
    {"can_loop_delay", offsetof(FaConfig, can_loop_delay), CFG_I32},
    {"led_on", offsetof(FaConfig, led_on), CFG_U8},
    {"led_highbeam_on", offsetof(FaConfig, led_highbeam_on), CFG_U8},
    {"led_mode", offsetof(FaConfig, led_mode), CFG_U8},
    {"led_mode_idle", offsetof(FaConfig, led_mode_idle), CFG_U8},
    {"led_mode_startup", offsetof(FaConfig, led_mode_startup), CFG_U8},
    {"led_mode_status", offsetof(FaConfig, led_mode_status), CFG_U8},
    {"led_mode_button", offsetof(FaConfig, led_mode_button), CFG_U8},
    {"led_mode_footpad", offsetof(FaConfig, led_mode_footpad), CFG_U8},
    {"led_mall_grab_enabled", offsetof(FaConfig, led_mall_grab_enabled), CFG_U8},
    {"led_brake_light_enabled", offsetof(FaConfig, led_brake_light_enabled), CFG_U8},
    {"led_brake_light_min_amps", offsetof(FaConfig, led_brake_light_min_amps), CFG_F32},
    {"idle_timeout", offsetof(FaConfig, idle_timeout), CFG_I32},
    {"idle_timeout_shutoff", offsetof(FaConfig, idle_timeout_shutoff), CFG_I32},
    {"led_brightness", offsetof(FaConfig, led_brightness), CFG_F32},
    {"led_brightness_highbeam", offsetof(FaConfig, led_brightness_highbeam), CFG_F32},
    {"led_brightness_idle", offsetof(FaConfig, led_brightness_idle), CFG_F32},
    {"led_brightness_status", offsetof(FaConfig, led_brightness_status), CFG_F32},
    {"led_max_brightness", offsetof(FaConfig, led_max_brightness), CFG_F32},
    {"led_dim_on_highbeam_ratio", offsetof(FaConfig, led_dim_on_highbeam_ratio), CFG_F32},
    {"led_startup_timeout", offsetof(FaConfig, led_startup_timeout), CFG_I32},
    {"led_loop_delay", offsetof(FaConfig, led_loop_delay), CFG_I32},
    {"led_update_not_running", offsetof(FaConfig, led_update_not_running), CFG_U8},
    {"led_show_battery_charging", offsetof(FaConfig, led_show_battery_charging), CFG_U8},
    {"led_front_strip_type", offsetof(FaConfig, led_front_strip_type), CFG_U8},
    {"led_front_pin", offsetof(FaConfig, led_front_pin), CFG_I32},
    {"led_front_num", offsetof(FaConfig, led_front_num), CFG_I32},
    {"led_front_type", offsetof(FaConfig, led_front_type), CFG_U8},
    {"led_front_reversed", offsetof(FaConfig, led_front_reversed), CFG_U8},
    {"led_front_highbeam_pin", offsetof(FaConfig, led_front_highbeam_pin), CFG_I32},
    {"led_rear_strip_type", offsetof(FaConfig, led_rear_strip_type), CFG_U8},
    {"led_rear_pin", offsetof(FaConfig, led_rear_pin), CFG_I32},
    {"led_rear_num", offsetof(FaConfig, led_rear_num), CFG_I32},
    {"led_rear_type", offsetof(FaConfig, led_rear_type), CFG_U8},
    {"led_rear_reversed", offsetof(FaConfig, led_rear_reversed), CFG_U8},
    {"led_rear_highbeam_pin", offsetof(FaConfig, led_rear_highbeam_pin), CFG_I32},
    {"led_status_strip_type", offsetof(FaConfig, led_status_strip_type), CFG_U8},
    {"led_status_pin", offsetof(FaConfig, led_status_pin), CFG_I32},
    {"led_status_num", offsetof(FaConfig, led_status_num), CFG_I32},
    {"led_status_type", offsetof(FaConfig, led_status_type), CFG_U8},
    {"led_status_reversed", offsetof(FaConfig, led_status_reversed), CFG_U8},
    {"led_footpad_strip_type", offsetof(FaConfig, led_footpad_strip_type), CFG_U8},
    {"led_footpad_pin", offsetof(FaConfig, led_footpad_pin), CFG_I32},
    {"led_footpad_num", offsetof(FaConfig, led_footpad_num), CFG_I32},
    {"led_footpad_type", offsetof(FaConfig, led_footpad_type), CFG_U8},
    {"led_footpad_reversed", offsetof(FaConfig, led_footpad_reversed), CFG_U8},
    {"led_button_strip_type", offsetof(FaConfig, led_button_strip_type), CFG_U8},
    {"led_button_pin", offsetof(FaConfig, led_button_pin), CFG_I32},
    {"pubmote_loop_delay", offsetof(FaConfig, pubmote_loop_delay), CFG_I32},
    {"pubmote_remote_mac_a", offsetof(FaConfig, pubmote_remote_mac_a), CFG_I32},
    {"pubmote_remote_mac_b", offsetof(FaConfig, pubmote_remote_mac_b), CFG_I32},
    {"pubmote_secret_code", offsetof(FaConfig, pubmote_secret_code), CFG_I32},
    {"bms_type", offsetof(FaConfig, bms_type), CFG_I32},
    {"bms_rs485_chip", offsetof(FaConfig, bms_rs485_chip), CFG_I32},
    {"bms_rs485_di_pin", offsetof(FaConfig, bms_rs485_di_pin), CFG_I32},
    {"bms_rs485_ro_pin", offsetof(FaConfig, bms_rs485_ro_pin), CFG_I32},
    {"bms_rs485_dere_pin", offsetof(FaConfig, bms_rs485_dere_pin), CFG_I32},
    {"bms_wakeup_pin", offsetof(FaConfig, bms_wakeup_pin), CFG_I32},
    {"bms_override_soc", offsetof(FaConfig, bms_override_soc), CFG_I32},
    {"bms_charge_only", offsetof(FaConfig, bms_charge_only), CFG_U8},
    {"bms_buff_size", offsetof(FaConfig, bms_buff_size), CFG_I32},
    {"bms_loop_delay", offsetof(FaConfig, bms_loop_delay), CFG_I32},
    {"soc_type", offsetof(FaConfig, soc_type), CFG_I32},
    {"cell_type", offsetof(FaConfig, cell_type), CFG_I32},
    {"bms_key_a", offsetof(FaConfig, bms_key_a), CFG_I32},
    {"bms_key_b", offsetof(FaConfig, bms_key_b), CFG_I32},
    {"bms_key_c", offsetof(FaConfig, bms_key_c), CFG_I32},
    {"bms_key_d", offsetof(FaConfig, bms_key_d), CFG_I32},
    {"bms_counter_a", offsetof(FaConfig, bms_counter_a), CFG_I32},
    {"bms_counter_b", offsetof(FaConfig, bms_counter_b), CFG_I32},
    {"bms_counter_c", offsetof(FaConfig, bms_counter_c), CFG_I32},
    {"bms_counter_d", offsetof(FaConfig, bms_counter_d), CFG_I32},
    {"log_rate", offsetof(FaConfig, log_rate), CFG_F32},
    {"log_append_gnss", offsetof(FaConfig, log_append_gnss), CFG_U8},
    {"humidity_sda_pin", offsetof(FaConfig, humidity_sda_pin), CFG_I32},
    {"humidity_slc_pin", offsetof(FaConfig, humidity_slc_pin), CFG_I32},
    {"accept_tos", offsetof(FaConfig, accept_tos), CFG_U8},
};

#define CFG_FIELD_COUNT (sizeof(cfg_fields) / sizeof(cfg_fields[0]))

// CONF_LOOKUP_H_
#endif
